name = "zyglz-auexue-blog"   # 项目名，可以改
compatibility_date = "2026-01-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"   # 这个不能动
database_name = "aiovtue-blog"   # 名字不一样也要改，最好一样
database_id = "fdeea008-0935-4f93-ad65-50712b561d31"  # 数据库id改成自己的

[[r2_buckets]]
binding = "BUCKET"   # 这个不能动
bucket_name = "aiovtue-blog"   # 名字不一样也要改，最好一样

[vars]
SITE_URL = "https:/blog.ttdd.top"
